version: "3.8"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: profilestats
        container_name: profilestats-app
        restart: unless-stopped
        networks:
            - profilestats
        ports:
            - 4000:80
        env_file: ./.env
    redis:
        image: redis:latest
        container_name: profilestats-redis
        restart: unless-stopped
        networks:
            - profilestats

networks:
    profilestats:
        driver: bridge
